# provisioning script

$script = <<SCRIPT

  # Install the docker repo
  cp /tmp/docker.repo /etc/yum.repos.d/docker.repo
  rm /tmp/docker.repo

  # Create docker group before docker installation
  # so the the file /var/run/docker.sock will belong to
  # the docker group
  #groupadd docker


  # Refresh yum cache
  yum makecache fast

  # Install yum packages
  yum install -y docker-engine
  yum install -y vim
  yum install -y git

  # Configure proxy for docker daemon
  sed -i '/[Service]/a Environment="HTTP_PROXY=http://proxy.priv.atos.fr:3128" "HTTPS_PROXY=http://proxy.priv.atos.fr:3128"' /usr/lib/systemd/system/docker.service  
  systemctl daemon-reload

  # Enable docker daemon on startup
  systemctl enable docker

  # Add vagrant user to docker group so it can use docker
  # client without sudo
  gpasswd -a vagrant docker


SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = "http://proxy.priv.atos.fr:3128"
    config.proxy.https = "http://proxy.priv.atos.fr:3128"
    config.proxy.no_proxy = "localhost,127.0.0.1,.sock,.priv.atos.fr,.qlf-waas.priv.atos.fr"
  end

  # Load the docker repo config to the guest
  config.vm.provision "file", source: "../docker.repo", destination: "/tmp/docker.repo"

  # Run provisioning
  config.vm.provision "shell", inline: $script

end
