# provisioning script

$script = <<SCRIPT

  # Install the docker repo
  cp /tmp/docker.repo /etc/yum.repos.d/docker.repo
  rm /tmp/docker.repo

  # Create docker group before docker installation
  # so the the file /var/run/docker.sock will belong to
  # the docker group
  #groupadd docker

  # Refresh yum cache
  yum makecache fast

  # Install yum packages
  yum install -y docker-engine
  yum install -y vim
  yum install -y git

  # Enable docker daemon on startup
  systemctl enable docker

  # Add vagrant user to docker group so it can use docker
  # client without sudo
  gpasswd -a vagrant docker


SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.1"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
  end

  # Load the docker repo config to the guest
  config.vm.provision "file", source: "../docker.repo", destination: "/tmp/docker.repo"

  # Run provisioning
  config.vm.provision "shell", inline: $script

end
